### ISSUE TITLE
Configure/disable all keyboard shortcut

### ISSUE THREAD

**Issue by yoshrat** [brimdata/react-arborist#119]
I want to use the tree using custom keyboard shortcut as it collide with other parts of my app,
Is there a way to do it?
Disabling all keyboard shortcut is also acceptable as I control the data and can drive the needed event using tree api.

Thanks

**Comment by jameskerr** [comment]
There is no way right now other than intercepting the keyboard events on the nodes and calling e.stopPropagation. There are plans to allow custom keyboard navigation settings.

**Comment by yoshrat** [comment]
I though about supplying my own RenderContainer, but the current implementation uses part of the package that  are not exported.
Is there a sample on how to supply my own container?

**Comment by jameskerr** [comment]
No, that DefaultContainer is in the docs but it's not really possible to provide your own because it uses all those external and internal libs.

But if you provide a custom RowRenderer, you can intercept the onMouseDown event and call stopPropagation on it. Then the event will not bubble up to the default container handler.

**Comment by jameskerr** [comment]
I will close this, but configurable keyboard shortcuts are being tracked here #57
