### ISSUE TITLE
Selection of internal node using keyboard

### ISSUE THREAD

**Issue by larrifax** [brimdata/react-arborist#141]
On leaf nodes, pressing `space` selects the node. On internal nodes, the same action toggles the collapsed state of the node, making it impossible to select it like you can using the mouse. Would it be possible to either change the behavior of `space` to also select internal nodes, or at least provide a boolean switch where we can toggle between the two behaviors?

The following lines of code shows the default behavior of the `space` keydown event:
https://github.com/brimdata/react-arborist/blob/main/packages/react-arborist/src/components/default-container.tsx#L175-L180

**Comment by jameskerr** [comment]
You make a good point. There is no way to select an internal node. Since the left and right arrows open and close nodes, it would make sense that the space key could select it.

When I set up these keyboard interactions I was guided by https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tree_role, and by looking at other Trees.

For example, this is the behavior for VSCode's tree view. The space key opens and closes folders, it does not select them.

https://github.com/brimdata/react-arborist/assets/3460638/9efd6d4a-b42f-45be-9f32-fe05a7137e4b

I will address this problem though by making the keyboard interaction mapping customizable. Then you could easily assign the space key to do whatever you'd like.

I'm going to close this in favor of #57

Thank you for your feedback!
