### ISSUE TITLE
Why not use `renderer` prop on `Tree` for NodeRenderer?

### ISSUE THREAD

**Issue by acjay** [brimdata/react-arborist#19]
I'm probably missing something, but it seems a little strange to me that the `Tree` component takes data for its children, rather than the more typical approach of children nodes being content to be passed in to a component. It seems like a more common approach would be to pass the node renderer as a prop to `Tree`. Which would probably mean that `Tree` would be a self-closing tag/component.

[I notice here](https://github.com/brimdata/react-arborist/blob/4c7363af6423f96b16c9fd6a9bb767a996451080/packages/react-arborist/src/components/tree.tsx#L69-L118) that the main `Tree` component implementation does, indeed, assign `children` to the `renderer` prop of `TreeViewProvider`, which appears to be the real workhorse component.

Suggestion: 
- create a `renderer` prop on `Tree`
- deprecate use of `Tree`'s children

**Comment by jameskerr** [comment]
Hi @acjay, thanks for writing up this suggestion. I know what you mean. It does seem a little strange. I based that API on the [react-window](https://react-window.vercel.app/#/examples/list/fixed-size) library, which is used by react-arborist. Brian passes in the row renderer as a single child component. 

Over time, it grew on me. It mirrors the hierarchy between the parent Tree component and the children Node components. 

Since React's children are just a special-case prop, I suppose you could make this argument for any component that accepts children. 

Why do we write...
```jsx
<Parent>
  <Child />
</Parent>
```
instead of...
```jsx
<Parent children={<Child />} />
```

I admit the way we use the "children" prop in the Tree is different than above, but it's at least a bit similar.

In the end I think this is just a "chocolate" or "vanilla" type decision, so I plan to leave the API as is.

However, I thank you for your time and for prompting me to think about this more.

**Comment by acjay** [comment]
Ok, gotcha. Yeah, I thought more about it and it seems like it's basically [a variation of the render prop pattern](https://reactjs.org/docs/render-props.html#using-props-other-than-render). I didn't recognize that with the `Node` pulled into a external variable, rather than provided inline as a closure.
